import { AppLanguage } from '../types';

// All supported languages
export const LANGUAGES = [
  { code: 'EN', name: 'English', flag: '🇺🇸' },
  { code: 'ES', name: 'Español', flag: '🇪🇸' },
  { code: 'FR', name: 'Français', flag: '🇫🇷' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'IT', name: 'Italiano', flag: '🇮🇹' },
  { code: 'PT', name: 'Português', flag: '🇧🇷' },
  { code: 'RU', name: 'Русский', flag: '🇷🇺' },
  { code: 'ZH', name: '中文', flag: '🇨🇳' },
  { code: 'JA', name: '日本語', flag: '🇯🇵' },
  { code: 'KO', name: '한국어', flag: '🇰🇷' },
  { code: 'AR', name: 'العربية', flag: '🇸🇦' },
  { code: 'HI', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'NL', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'PL', name: 'Polski', flag: '🇵🇱' },
  { code: 'TR', name: 'Türkçe', flag: '🇹🇷' },
];

const translations: Record<string, Record<string, string>> = {
  EN: {
    // Navigation & Common
    home: 'Home',
    back: 'Back',
    share: 'Share',
    donate: 'Donate',
    upgrade: 'Upgrade',
    settings: 'Settings',
    signOut: 'Sign Out',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit',
    loading: 'Loading...',
    processing: 'Processing...',
    success: 'Success!',
    error: 'Error',
    tryAgain: 'Try Again',
    continue: 'Continue',
    start: 'Start',
    stop: 'Stop',
    record: 'Record',
    play: 'Play',
    pause: 'Pause',
    download: 'Download',
    copy: 'Copy',
    
    // Hero Section
    heroTitle: 'AI MUSIC STUDIO',
    heroSubtitle: 'Sing 4 words to write a hit, get judged by AI, and master your vocals.',
    tagline: 'Sing 4 Words → AI Creates YOUR Song → Earn Your Golden Ticket! 🎫',
    unlockPotential: 'Unlock Full Potential',
    loadingStudio: 'Loading Studio...',
    
    // Main Menu Items
    voiceClone: 'Voice Clone',
    voiceCloneDesc: 'Train your voice with fun phrases!',
    voiceCloner: 'Song Writer',
    voiceClonerDesc: 'Sing 4 words, get a hit song tailored to your style.',
    lyricComposer: 'Lyric Composer',
    lyricComposerDesc: 'Lyrics to music. We compose the arrangement.',
    judge: 'The Judge',
    judgeDesc: 'Get a real America\'s Got Talent readiness score.',
    idolPrep: 'AGT Prep Course',
    idolPrepDesc: 'Win the Golden Ticket. Audition training & feedback.',
    duet: 'Duet Mode',
    duetDesc: 'Sing with an AI partner in real-time.',
    vocalCoach: 'Vocal Coach',
    vocalCoachDesc: 'Master your range with AI exercises.',
    stagePresence: 'Stage Presence',
    stagePresenceDesc: 'Learn to command the crowd.',
    danceCoach: 'Dance Coach',
    danceCoachDesc: 'AI video dance lessons for the stage!',
    singingLessons: 'Singing Lessons',
    singingLessonsDesc: 'AI vocal training from breathing to belting!',
    branding: 'Star Identity',
    brandingDesc: 'Create your brand and look.',
    shop: 'Merch Shop',
    shopDesc: 'Get exclusive StarPrep merchandise.',
    
    // Voice Clone Mode
    trainYourVoice: 'Train Your Voice',
    voiceTrainingComplete: 'Voice Training Complete!',
    voiceReady: 'Your voice is ready!',
    startVoiceTraining: 'Start Voice Training',
    retrainVoice: 'Retrain Voice',
    readPhrasesAloud: 'Read 4 fun phrases out loud and we\'ll learn your unique voice!',
    funPhrases: 'Including "My dog can\'t swim" and other hilarious phrases!',
    howVoiceCloneWorks: 'How Voice Clone Works',
    step1Voice: 'Read 4 funny phrases out loud',
    step2Voice: 'AI learns your unique voice',
    step3Voice: 'Songs are created in YOUR voice!',
    
    // Voice Setup
    voiceSetupTitle: 'Voice Training',
    voiceSetupIntro: 'Let\'s train your voice! Read these fun phrases out loud.',
    phrase: 'Phrase',
    of: 'of',
    pressToRecord: 'Press to record',
    recording: 'Recording...',
    recorded: 'Recorded!',
    nextPhrase: 'Next Phrase',
    finishTraining: 'Finish Training',
    greatJob: 'Great job!',
    keepGoing: 'Keep going!',
    almostThere: 'Almost there!',
    perfectRecording: 'Perfect recording!',
    
    // Song Writer Mode
    songWriter: 'Song Writer',
    songWriterDesc: 'Sing just 4 words and our AI will compose a complete song with lyrics, melody suggestions, and structure.',
    setupMyVoice: 'Setup My Voice',
    voiceReadyBtn: 'Voice Ready',
    recordYourWords: 'Record Your 4 Words',
    singFourWords: 'Sing any 4 words clearly',
    uploadAudio: 'Upload Audio',
    dragDropAudio: 'Drag & drop audio file or click to browse',
    generatingSong: 'Generating your song...',
    transcribingAudio: 'Transcribing your audio...',
    creatingLyrics: 'Creating lyrics from your words...',
    composingMelody: 'Composing melody...',
    yourDetectedWords: 'Your detected words',
    generateMusic: 'Generate Music',
    generateWithMyVoice: 'Generate with My Voice',
    newSong: 'New Song',
    
    // Judge Mode
    judgeTitle: 'The Judge',
    judgeSubtitle: 'Perform your best and get scored like you\'re on America\'s Got Talent!',
    pressAndPerform: 'Press the button and perform your best!',
    singYourHeartOut: 'Sing your heart out!',
    singFor15Seconds: 'Sing for at least 15 seconds for best results',
    recordingCaptured: 'Recording captured!',
    getJudged: 'Get Judged!',
    judging: 'Judging...',
    judgesDeliberating: 'The Judges are deliberating...',
    analyzingPerformance: 'Analyzing your pitch, timing, and emotion',
    goldenTicket: 'GOLDEN TICKET!',
    goingToHollywood: 'You\'re going to Hollywood!',
    yourScores: 'Your Scores',
    pitchAccuracy: 'Pitch Accuracy',
    timingRhythm: 'Timing & Rhythm',
    emotionExpression: 'Emotion & Expression',
    overallScore: 'Overall Score',
    judgeFeedback: 'Judge\'s Feedback',
    performAgain: 'Perform Again',
    performanceTips: 'Performance Tips',
    tip1: 'Sing in a quiet environment for best results',
    tip2: 'Perform for at least 15-30 seconds',
    tip3: 'Put emotion into your performance',
    tip4: 'Hold your device close like a microphone',
    tip5: 'Aim for 95%+ to earn your Golden Ticket!',
    
    // Lyric Composer Mode
    lyricComposerTitle: 'Lyric Composer',
    lyricComposerSubtitle: 'Tell us your topic and we\'ll write you a hit song!',
    whatsSongAbout: 'What\'s your song about?',
    topicPlaceholder: 'e.g., summer love, my dog can\'t swim, chasing dreams...',
    pickYourMood: 'Pick your mood',
    moodHappy: 'Happy',
    moodSad: 'Sad',
    moodLove: 'Love',
    moodAngry: 'Angry',
    moodChill: 'Chill',
    moodHype: 'Hype',
    chooseGenre: 'Choose your genre',
    genrePop: 'Pop',
    genreRnb: 'R&B',
    genreHiphop: 'Hip-Hop',
    genreRock: 'Rock',
    genreCountry: 'Country',
    genreBallad: 'Ballad',
    composeMySong: 'Compose My Song!',
    composing: 'Composing...',
    copiedToClipboard: 'Lyrics copied to clipboard!',
    
    // Donate Modal
    everyChildDeservesMusic: 'Every Child Deserves Music',
    donateMessage1: 'Across the country, school music programs are being cut due to budget constraints.',
    donateMessage2: 'Thousands of children who dream of singing, playing guitar, or joining the school band can\'t afford instruments.',
    donateMessage3: 'Your donation helps put instruments in the hands of kids who otherwise would never get the chance to discover their musical talent.',
    donateMessage4: 'You could help create the next star!',
    iWantToHelp: 'I Want to Help!',
    chooseYourDonation: 'Choose Your Donation',
    goesToKids: '100% goes to instruments for kids in need',
    selectAmount: 'Select Amount',
    donateWithCard: 'Donate with Card',
    thankYouDonation: 'Thank You!',
    donationReceived: 'Your generosity will help a child discover their musical dreams.',
    youreAStar: 'You\'re a star!',
    
    // Settings
    settingsTitle: 'Settings',
    membership: 'Membership',
    support: 'Support',
    legal: 'Legal',
    system: 'System',
    about: 'About',
    language: 'Language',
    selectLanguage: 'Select Language',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    
    // Pricing
    freeTier: 'Free',
    proTier: 'Pro',
    superstarTier: 'Superstar',
    perMonth: '/month',
    mostPopular: 'Most Popular',
    currentPlan: 'Current Plan',
    choosePlan: 'Choose Plan',
    
    // Misc
    noAudioDetected: 'No words detected in audio. Please try again and speak clearly.',
    microphoneError: 'Could not access microphone. Please check permissions.',
    generationFailed: 'Generation failed. Please try again.',
    
    // Footer & Legal
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    contactUs: 'Contact Us',
    copyright: '© 2024 StarPrepAI. All rights reserved.',
  },
  
  ES: {
    // Navigation & Common
    home: 'Inicio',
    back: 'Atrás',
    share: 'Compartir',
    donate: 'Donar',
    upgrade: 'Mejorar',
    settings: 'Configuración',
    signOut: 'Cerrar Sesión',
    close: 'Cerrar',
    cancel: 'Cancelar',
    save: 'Guardar',
    submit: 'Enviar',
    loading: 'Cargando...',
    processing: 'Procesando...',
    success: '¡Éxito!',
    error: 'Error',
    tryAgain: 'Intentar de Nuevo',
    continue: 'Continuar',
    start: 'Iniciar',
    stop: 'Detener',
    record: 'Grabar',
    play: 'Reproducir',
    pause: 'Pausar',
    download: 'Descargar',
    copy: 'Copiar',
    
    // Hero Section
    heroTitle: 'ESTUDIO DE MÚSICA IA',
    heroSubtitle: 'Canta 4 palabras para escribir un éxito, sé juzgado por IA y domina tu voz.',
    tagline: 'Tu Camino al Estrellato con IA',
    unlockPotential: 'Desbloquea Tu Potencial',
    loadingStudio: 'Cargando Estudio...',
    
    // Main Menu Items
    voiceClone: 'Clonar Voz',
    voiceCloneDesc: '¡Entrena tu voz con frases divertidas!',
    voiceCloner: 'Compositor',
    voiceClonerDesc: 'Canta 4 palabras, obtén una canción a tu estilo.',
    lyricComposer: 'Compositor de Letras',
    lyricComposerDesc: 'Letras a música. Componemos el arreglo.',
    judge: 'El Juez',
    judgeDesc: 'Obtén una puntuación real de America\'s Got Talent.',
    idolPrep: 'Curso Preparación AGT',
    idolPrepDesc: 'Gana el Boleto Dorado. Entrenamiento para audiciones.',
    duet: 'Modo Dúo',
    duetDesc: 'Canta con un compañero IA en tiempo real.',
    vocalCoach: 'Coach Vocal',
    vocalCoachDesc: 'Domina tu rango con ejercicios de IA.',
    stagePresence: 'Presencia Escénica',
    stagePresenceDesc: 'Aprende a dominar al público.',
    danceCoach: 'Coach de Baile',
    danceCoachDesc: '¡Lecciones de baile con video IA para el escenario!',
    singingLessons: 'Clases de Canto',
    singingLessonsDesc: '¡Entrenamiento vocal con IA desde respiración hasta potencia!',
    branding: 'Identidad Estelar',
    brandingDesc: 'Crea tu marca y estilo.',
    shop: 'Tienda',
    shopDesc: 'Obtén mercancía exclusiva de StarPrep.',
    
    // Voice Clone Mode
    trainYourVoice: 'Entrena Tu Voz',
    voiceTrainingComplete: '¡Entrenamiento de Voz Completo!',
    voiceReady: '¡Tu voz está lista!',
    startVoiceTraining: 'Iniciar Entrenamiento de Voz',
    retrainVoice: 'Reentrenar Voz',
    readPhrasesAloud: '¡Lee 4 frases divertidas en voz alta y aprenderemos tu voz única!',
    funPhrases: '¡Incluyendo "Mi perro no sabe nadar" y otras frases divertidas!',
    howVoiceCloneWorks: 'Cómo Funciona el Clon de Voz',
    step1Voice: 'Lee 4 frases divertidas en voz alta',
    step2Voice: 'La IA aprende tu voz única',
    step3Voice: '¡Las canciones se crean con TU voz!',
    
    // Voice Setup
    voiceSetupTitle: 'Entrenamiento de Voz',
    voiceSetupIntro: '¡Vamos a entrenar tu voz! Lee estas frases divertidas en voz alta.',
    phrase: 'Frase',
    of: 'de',
    pressToRecord: 'Presiona para grabar',
    recording: 'Grabando...',
    recorded: '¡Grabado!',
    nextPhrase: 'Siguiente Frase',
    finishTraining: 'Terminar Entrenamiento',
    greatJob: '¡Buen trabajo!',
    keepGoing: '¡Sigue así!',
    almostThere: '¡Casi llegas!',
    perfectRecording: '¡Grabación perfecta!',
    
    // Song Writer Mode
    songWriter: 'Compositor de Canciones',
    songWriterDesc: 'Canta solo 4 palabras y nuestra IA compondrá una canción completa con letra, melodía y estructura.',
    setupMyVoice: 'Configurar Mi Voz',
    voiceReadyBtn: 'Voz Lista',
    recordYourWords: 'Graba Tus 4 Palabras',
    singFourWords: 'Canta cualquier 4 palabras claramente',
    uploadAudio: 'Subir Audio',
    dragDropAudio: 'Arrastra y suelta archivo de audio o haz clic para buscar',
    generatingSong: 'Generando tu canción...',
    transcribingAudio: 'Transcribiendo tu audio...',
    creatingLyrics: 'Creando letras de tus palabras...',
    composingMelody: 'Componiendo melodía...',
    yourDetectedWords: 'Tus palabras detectadas',
    generateMusic: 'Generar Música',
    generateWithMyVoice: 'Generar con Mi Voz',
    newSong: 'Nueva Canción',
    
    // Judge Mode
    judgeTitle: 'El Juez',
    judgeSubtitle: '¡Haz tu mejor actuación y recibe puntuación como en America\'s Got Talent!',
    pressAndPerform: '¡Presiona el botón y da tu mejor actuación!',
    singYourHeartOut: '¡Canta con el corazón!',
    singFor15Seconds: 'Canta al menos 15 segundos para mejores resultados',
    recordingCaptured: '¡Grabación capturada!',
    getJudged: '¡Ser Juzgado!',
    judging: 'Juzgando...',
    judgesDeliberating: 'Los jueces están deliberando...',
    analyzingPerformance: 'Analizando tu tono, tiempo y emoción',
    goldenTicket: '¡BOLETO DORADO!',
    goingToHollywood: '¡Vas a Hollywood!',
    yourScores: 'Tus Puntuaciones',
    pitchAccuracy: 'Precisión de Tono',
    timingRhythm: 'Tiempo y Ritmo',
    emotionExpression: 'Emoción y Expresión',
    overallScore: 'Puntuación General',
    judgeFeedback: 'Comentarios del Juez',
    performAgain: 'Actuar de Nuevo',
    performanceTips: 'Consejos de Actuación',
    tip1: 'Canta en un ambiente tranquilo para mejores resultados',
    tip2: 'Actúa durante al menos 15-30 segundos',
    tip3: 'Pon emoción en tu actuación',
    tip4: 'Sostén tu dispositivo cerca como un micrófono',
    tip5: '¡Apunta a 95%+ para ganar tu Boleto Dorado!',
    
    // Lyric Composer Mode
    lyricComposerTitle: 'Compositor de Letras',
    lyricComposerSubtitle: '¡Dinos tu tema y te escribiremos una canción exitosa!',
    whatsSongAbout: '¿De qué trata tu canción?',
    topicPlaceholder: 'ej., amor de verano, mi perro no nada, persiguiendo sueños...',
    pickYourMood: 'Elige tu estado de ánimo',
    moodHappy: 'Feliz',
    moodSad: 'Triste',
    moodLove: 'Amor',
    moodAngry: 'Enojado',
    moodChill: 'Relajado',
    moodHype: 'Energético',
    chooseGenre: 'Elige tu género',
    genrePop: 'Pop',
    genreRnb: 'R&B',
    genreHiphop: 'Hip-Hop',
    genreRock: 'Rock',
    genreCountry: 'Country',
    genreBallad: 'Balada',
    composeMySong: '¡Componer Mi Canción!',
    composing: 'Componiendo...',
    copiedToClipboard: '¡Letra copiada al portapapeles!',
    
    // Donate Modal
    everyChildDeservesMusic: 'Cada Niño Merece Música',
    donateMessage1: 'En todo el país, los programas de música escolar están siendo recortados debido a restricciones presupuestarias.',
    donateMessage2: 'Miles de niños que sueñan con cantar, tocar guitarra o unirse a la banda escolar no pueden pagar instrumentos.',
    donateMessage3: 'Tu donación ayuda a poner instrumentos en manos de niños que de otra manera nunca tendrían la oportunidad de descubrir su talento musical.',
    donateMessage4: '¡Podrías ayudar a crear la próxima estrella!',
    iWantToHelp: '¡Quiero Ayudar!',
    chooseYourDonation: 'Elige Tu Donación',
    goesToKids: '100% va a instrumentos para niños necesitados',
    selectAmount: 'Seleccionar Cantidad',
    donateWithCard: 'Donar con Tarjeta',
    thankYouDonation: '¡Gracias!',
    donationReceived: 'Tu generosidad ayudará a un niño a descubrir sus sueños musicales.',
    youreAStar: '¡Eres una estrella!',
    
    // Settings
    settingsTitle: 'Configuración',
    membership: 'Membresía',
    support: 'Soporte',
    legal: 'Legal',
    system: 'Sistema',
    about: 'Acerca de',
    language: 'Idioma',
    selectLanguage: 'Seleccionar Idioma',
    darkMode: 'Modo Oscuro',
    notifications: 'Notificaciones',
    
    // Pricing
    freeTier: 'Gratis',
    proTier: 'Pro',
    superstarTier: 'Superestrella',
    perMonth: '/mes',
    mostPopular: 'Más Popular',
    currentPlan: 'Plan Actual',
    choosePlan: 'Elegir Plan',
    
    // Misc
    noAudioDetected: 'No se detectaron palabras en el audio. Por favor intenta de nuevo y habla claramente.',
    microphoneError: 'No se pudo acceder al micrófono. Por favor verifica los permisos.',
    generationFailed: 'La generación falló. Por favor intenta de nuevo.',
    
    // Footer & Legal
    termsOfService: 'Términos de Servicio',
    privacyPolicy: 'Política de Privacidad',
    contactUs: 'Contáctanos',
    copyright: '© 2024 StarPrepAI. Todos los derechos reservados.',
  },
  
  FR: {
    home: 'Accueil',
    back: 'Retour',
    share: 'Partager',
    donate: 'Faire un Don',
    upgrade: 'Améliorer',
    settings: 'Paramètres',
    signOut: 'Déconnexion',
    close: 'Fermer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    submit: 'Soumettre',
    loading: 'Chargement...',
    processing: 'Traitement...',
    success: 'Succès!',
    error: 'Erreur',
    tryAgain: 'Réessayer',
    continue: 'Continuer',
    start: 'Démarrer',
    stop: 'Arrêter',
    record: 'Enregistrer',
    play: 'Lire',
    pause: 'Pause',
    download: 'Télécharger',
    copy: 'Copier',
    heroTitle: 'STUDIO DE MUSIQUE IA',
    heroSubtitle: 'Chantez 4 mots pour écrire un hit, soyez jugé par l\'IA et maîtrisez votre voix.',
    tagline: 'Votre Chemin vers la Célébrité avec l\'IA',
    unlockPotential: 'Débloquez Votre Potentiel',
    loadingStudio: 'Chargement du Studio...',
    voiceClone: 'Cloner la Voix',
    voiceCloneDesc: 'Entraînez votre voix avec des phrases amusantes!',
    voiceCloner: 'Compositeur',
    voiceClonerDesc: 'Chantez 4 mots, obtenez une chanson à votre style.',
    lyricComposer: 'Compositeur de Paroles',
    lyricComposerDesc: 'Paroles en musique. Nous composons l\'arrangement.',
    judge: 'Le Juge',
    judgeDesc: 'Obtenez un score réel de préparation America\'s Got Talent.',
    idolPrep: 'Cours de Préparation AGT',
    idolPrepDesc: 'Gagnez le Ticket d\'Or. Formation et retour d\'audition.',
    duet: 'Mode Duo',
    duetDesc: 'Chantez avec un partenaire IA en temps réel.',
    vocalCoach: 'Coach Vocal',
    vocalCoachDesc: 'Maîtrisez votre gamme avec des exercices d\'IA.',
    stagePresence: 'Présence Scénique',
    stagePresenceDesc: 'Apprenez à commander la foule.',
    danceCoach: 'Coach de Danse',
    danceCoachDesc: 'Cours de danse vidéo IA pour la scène!',
    singingLessons: 'Cours de Chant',
    singingLessonsDesc: 'Formation vocale IA de la respiration au belting!',
    branding: 'Identité d\'Étoile',
    brandingDesc: 'Créez votre marque et votre look.',
    shop: 'Boutique',
    shopDesc: 'Obtenez des produits exclusifs StarPrep.',
    trainYourVoice: 'Entraînez Votre Voix',
    voiceTrainingComplete: 'Entraînement Vocal Terminé!',
    voiceReady: 'Votre voix est prête!',
    startVoiceTraining: 'Commencer l\'Entraînement Vocal',
    retrainVoice: 'Réentraîner la Voix',
    readPhrasesAloud: 'Lisez 4 phrases amusantes à voix haute et nous apprendrons votre voix unique!',
    funPhrases: 'Y compris "Mon chien ne sait pas nager" et autres phrases hilarantes!',
    howVoiceCloneWorks: 'Comment Fonctionne le Clone Vocal',
    step1Voice: 'Lisez 4 phrases amusantes à voix haute',
    step2Voice: 'L\'IA apprend votre voix unique',
    step3Voice: 'Les chansons sont créées avec VOTRE voix!',
    songWriter: 'Compositeur de Chansons',
    songWriterDesc: 'Chantez seulement 4 mots et notre IA composera une chanson complète.',
    setupMyVoice: 'Configurer Ma Voix',
    voiceReadyBtn: 'Voix Prête',
    recordYourWords: 'Enregistrez Vos 4 Mots',
    singFourWords: 'Chantez 4 mots clairement',
    generateMusic: 'Générer la Musique',
    generateWithMyVoice: 'Générer avec Ma Voix',
    newSong: 'Nouvelle Chanson',
    judgeTitle: 'Le Juge',
    judgeSubtitle: 'Faites votre meilleure performance et recevez un score!',
    goldenTicket: 'TICKET D\'OR!',
    goingToHollywood: 'Vous allez à Hollywood!',
    yourScores: 'Vos Scores',
    pitchAccuracy: 'Précision du Ton',
    timingRhythm: 'Timing et Rythme',
    emotionExpression: 'Émotion et Expression',
    overallScore: 'Score Global',
    performAgain: 'Rejouer',
    everyChildDeservesMusic: 'Chaque Enfant Mérite la Musique',
    iWantToHelp: 'Je Veux Aider!',
    chooseYourDonation: 'Choisissez Votre Don',
    thankYouDonation: 'Merci!',
    youreAStar: 'Vous êtes une star!',
    language: 'Langue',
    selectLanguage: 'Sélectionner la Langue',
  },
  
  DE: {
    home: 'Startseite',
    back: 'Zurück',
    share: 'Teilen',
    donate: 'Spenden',
    upgrade: 'Upgraden',
    settings: 'Einstellungen',
    signOut: 'Abmelden',
    close: 'Schließen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    submit: 'Absenden',
    loading: 'Laden...',
    processing: 'Verarbeitung...',
    success: 'Erfolg!',
    error: 'Fehler',
    tryAgain: 'Erneut Versuchen',
    continue: 'Weiter',
    start: 'Starten',
    stop: 'Stoppen',
    record: 'Aufnehmen',
    play: 'Abspielen',
    pause: 'Pause',
    download: 'Herunterladen',
    copy: 'Kopieren',
    heroTitle: 'KI-MUSIKSTUDIO',
    heroSubtitle: 'Sing 4 Wörter, um einen Hit zu schreiben, werde von KI bewertet und meistere deine Stimme.',
    tagline: 'Dein KI-Weg zum Ruhm',
    unlockPotential: 'Entfessle Dein Potenzial',
    loadingStudio: 'Studio wird geladen...',
    voiceClone: 'Stimme Klonen',
    voiceCloneDesc: 'Trainiere deine Stimme mit lustigen Sätzen!',
    voiceCloner: 'Komponist',
    voiceClonerDesc: 'Sing 4 Wörter, erhalte einen Hit-Song.',
    lyricComposer: 'Textkomponist',
    lyricComposerDesc: 'Text zu Musik. Wir komponieren das Arrangement.',
    judge: 'Der Richter',
    judgeDesc: 'Erhalte eine echte AGT-Bereitschaftsbewertung.',
    idolPrep: 'AGT Vorbereitungskurs',
    idolPrepDesc: 'Gewinne das Goldene Ticket.',
    duet: 'Duett-Modus',
    duetDesc: 'Sing mit einem KI-Partner in Echtzeit.',
    vocalCoach: 'Gesangscoach',
    vocalCoachDesc: 'Meistere deine Stimmlage mit KI-Übungen.',
    stagePresence: 'Bühnenpräsenz',
    stagePresenceDesc: 'Lerne, die Menge zu beherrschen.',
    danceCoach: 'Tanzcoach',
    danceCoachDesc: 'KI-Video-Tanzstunden für die Bühne!',
    singingLessons: 'Gesangsunterricht',
    singingLessonsDesc: 'KI-Stimmtraining von Atmung bis Belting!',
    branding: 'Star-Identität',
    brandingDesc: 'Erstelle deine Marke und deinen Look.',
    shop: 'Shop',
    shopDesc: 'Hol dir exklusive StarPrep-Artikel.',
    trainYourVoice: 'Trainiere Deine Stimme',
    voiceTrainingComplete: 'Stimmtraining Abgeschlossen!',
    voiceReady: 'Deine Stimme ist bereit!',
    startVoiceTraining: 'Stimmtraining Starten',
    retrainVoice: 'Stimme Neu Trainieren',
    goldenTicket: 'GOLDENES TICKET!',
    goingToHollywood: 'Du gehst nach Hollywood!',
    everyChildDeservesMusic: 'Jedes Kind Verdient Musik',
    iWantToHelp: 'Ich Will Helfen!',
    thankYouDonation: 'Danke!',
    youreAStar: 'Du bist ein Star!',
    language: 'Sprache',
    selectLanguage: 'Sprache Auswählen',
  },
  
  IT: {
    home: 'Home',
    back: 'Indietro',
    share: 'Condividi',
    donate: 'Dona',
    upgrade: 'Aggiorna',
    settings: 'Impostazioni',
    signOut: 'Esci',
    close: 'Chiudi',
    loading: 'Caricamento...',
    heroTitle: 'STUDIO MUSICALE IA',
    heroSubtitle: 'Canta 4 parole per scrivere un successo, fatti giudicare dall\'IA e padroneggia la tua voce.',
    tagline: 'Il Tuo Percorso verso il Successo con l\'IA',
    voiceClone: 'Clona Voce',
    voiceCloneDesc: 'Allena la tua voce con frasi divertenti!',
    judge: 'Il Giudice',
    judgeDesc: 'Ottieni un punteggio reale di preparazione AGT.',
    danceCoach: 'Coach di Danza',
    danceCoachDesc: 'Lezioni di danza video AI per il palco!',
    goldenTicket: 'BIGLIETTO D\'ORO!',
    goingToHollywood: 'Stai andando a Hollywood!',
    everyChildDeservesMusic: 'Ogni Bambino Merita la Musica',
    iWantToHelp: 'Voglio Aiutare!',
    thankYouDonation: 'Grazie!',
    youreAStar: 'Sei una stella!',
    language: 'Lingua',
    selectLanguage: 'Seleziona Lingua',
  },
  
  PT: {
    home: 'Início',
    back: 'Voltar',
    share: 'Compartilhar',
    donate: 'Doar',
    upgrade: 'Atualizar',
    settings: 'Configurações',
    signOut: 'Sair',
    close: 'Fechar',
    loading: 'Carregando...',
    heroTitle: 'ESTÚDIO DE MÚSICA IA',
    heroSubtitle: 'Cante 4 palavras para escrever um hit, seja julgado pela IA e domine sua voz.',
    tagline: 'Seu Caminho para o Estrelato com IA',
    voiceClone: 'Clonar Voz',
    voiceCloneDesc: 'Treine sua voz com frases divertidas!',
    judge: 'O Juiz',
    judgeDesc: 'Obtenha uma pontuação real de preparação para o AGT.',
    danceCoach: 'Coach de Dança',
    danceCoachDesc: 'Aulas de dança em vídeo com IA para o palco!',
    goldenTicket: 'BILHETE DOURADO!',
    goingToHollywood: 'Você vai para Hollywood!',
    everyChildDeservesMusic: 'Toda Criança Merece Música',
    iWantToHelp: 'Eu Quero Ajudar!',
    thankYouDonation: 'Obrigado!',
    youreAStar: 'Você é uma estrela!',
    language: 'Idioma',
    selectLanguage: 'Selecionar Idioma',
  },
  
  RU: {
    home: 'Главная',
    back: 'Назад',
    share: 'Поделиться',
    donate: 'Пожертвовать',
    upgrade: 'Улучшить',
    settings: 'Настройки',
    signOut: 'Выйти',
    close: 'Закрыть',
    loading: 'Загрузка...',
    heroTitle: 'ИИ МУЗЫКАЛЬНАЯ СТУДИЯ',
    heroSubtitle: 'Спой 4 слова, чтобы написать хит, получи оценку от ИИ и овладей своим голосом.',
    tagline: 'Твой Путь к Славе с ИИ',
    voiceClone: 'Клонировать Голос',
    voiceCloneDesc: 'Тренируй свой голос с веселыми фразами!',
    judge: 'Судья',
    judgeDesc: 'Получи реальную оценку готовности к AGT.',
    danceCoach: 'Танцевальный Тренер',
    danceCoachDesc: 'Видеоуроки танцев с ИИ для сцены!',
    goldenTicket: 'ЗОЛОТОЙ БИЛЕТ!',
    goingToHollywood: 'Ты едешь в Голливуд!',
    everyChildDeservesMusic: 'Каждый Ребенок Заслуживает Музыку',
    iWantToHelp: 'Я Хочу Помочь!',
    thankYouDonation: 'Спасибо!',
    youreAStar: 'Ты звезда!',
    language: 'Язык',
    selectLanguage: 'Выбрать Язык',
  },
  
  ZH: {
    home: '首页',
    back: '返回',
    share: '分享',
    donate: '捐赠',
    upgrade: '升级',
    settings: '设置',
    signOut: '退出',
    close: '关闭',
    loading: '加载中...',
    heroTitle: 'AI音乐工作室',
    heroSubtitle: '唱4个词写出热门歌曲，接受AI评判，精通声乐。',
    tagline: '你的AI明星之路',
    voiceClone: '克隆声音',
    voiceCloneDesc: '用有趣的短语训练你的声音！',
    judge: '评委',
    judgeDesc: '获得真正的AGT准备分数。',
    danceCoach: '舞蹈教练',
    danceCoachDesc: 'AI视频舞蹈课程，为舞台准备！',
    singingLessons: '唱歌课程',
    singingLessonsDesc: '从呼吸到高音的AI声乐训练！',
    goldenTicket: '金票！',
    goingToHollywood: '你要去好莱坞了！',
    everyChildDeservesMusic: '每个孩子都值得拥有音乐',
    iWantToHelp: '我想帮忙！',
    thankYouDonation: '谢谢！',
    youreAStar: '你是明星！',
    language: '语言',
    selectLanguage: '选择语言',
  },
  
  JA: {
    home: 'ホーム',
    back: '戻る',
    share: '共有',
    donate: '寄付',
    upgrade: 'アップグレード',
    settings: '設定',
    signOut: 'サインアウト',
    close: '閉じる',
    loading: '読み込み中...',
    heroTitle: 'AI音楽スタジオ',
    heroSubtitle: '4語歌ってヒット曲を作り、AIに審査され、ボーカルをマスターしよう。',
    tagline: 'AIによるスターへの道',
    voiceClone: 'ボイスクローン',
    voiceCloneDesc: '楽しいフレーズで声をトレーニング！',
    judge: '審査員',
    judgeDesc: '本物のAGT準備スコアを取得。',
    danceCoach: 'ダンスコーチ',
    danceCoachDesc: 'ステージのためのAIビデオダンスレッスン！',
    singingLessons: '歌唱レッスン',
    singingLessonsDesc: '呼吸からベルティングまでのAIボーカルトレーニング！',
    goldenTicket: 'ゴールデンチケット！',
    goingToHollywood: 'ハリウッドへ行こう！',
    everyChildDeservesMusic: 'すべての子供に音楽を',
    iWantToHelp: '助けたい！',
    thankYouDonation: 'ありがとう！',
    youreAStar: 'あなたはスター！',
    language: '言語',
    selectLanguage: '言語を選択',
  },
  
  KO: {
    home: '홈',
    back: '뒤로',
    share: '공유',
    donate: '기부',
    upgrade: '업그레이드',
    settings: '설정',
    signOut: '로그아웃',
    close: '닫기',
    loading: '로딩 중...',
    heroTitle: 'AI 음악 스튜디오',
    heroSubtitle: '4단어를 불러 히트곡을 쓰고, AI의 심사를 받고, 보컬을 마스터하세요.',
    tagline: 'AI와 함께하는 스타의 길',
    voiceClone: '보이스 클론',
    voiceCloneDesc: '재미있는 문구로 목소리를 훈련하세요!',
    judge: '심사위원',
    judgeDesc: '실제 AGT 준비 점수를 받으세요.',
    danceCoach: '댄스 코치',
    danceCoachDesc: '무대를 위한 AI 비디오 댄스 레슨!',
    singingLessons: '노래 레슨',
    singingLessonsDesc: '호흡부터 벨팅까지 AI 보컬 트레이닝!',
    goldenTicket: '골든 티켓!',
    goingToHollywood: '할리우드로 가요!',
    everyChildDeservesMusic: '모든 아이는 음악을 누릴 자격이 있습니다',
    iWantToHelp: '돕고 싶어요!',
    thankYouDonation: '감사합니다!',
    youreAStar: '당신은 스타예요!',
    language: '언어',
    selectLanguage: '언어 선택',
  },
  
  AR: {
    home: 'الرئيسية',
    back: 'رجوع',
    share: 'مشاركة',
    donate: 'تبرع',
    upgrade: 'ترقية',
    settings: 'الإعدادات',
    signOut: 'تسجيل الخروج',
    close: 'إغلاق',
    loading: 'جاري التحميل...',
    heroTitle: 'استوديو الموسيقى بالذكاء الاصطناعي',
    heroSubtitle: 'غنِّ 4 كلمات لكتابة أغنية ناجحة، واحصل على تقييم من الذكاء الاصطناعي.',
    tagline: 'طريقك للنجومية مع الذكاء الاصطناعي',
    voiceClone: 'استنساخ الصوت',
    voiceCloneDesc: 'درّب صوتك بعبارات ممتعة!',
    judge: 'الحكم',
    judgeDesc: 'احصل على درجة استعداد حقيقية.',
    danceCoach: 'مدرب الرقص',
    danceCoachDesc: 'دروس رقص فيديو بالذكاء الاصطناعي للمسرح!',
    goldenTicket: 'التذكرة الذهبية!',
    goingToHollywood: 'أنت ذاهب إلى هوليوود!',
    everyChildDeservesMusic: 'كل طفل يستحق الموسيقى',
    iWantToHelp: 'أريد المساعدة!',
    thankYouDonation: 'شكراً لك!',
    youreAStar: 'أنت نجم!',
    language: 'اللغة',
    selectLanguage: 'اختر اللغة',
  },
  
  HI: {
    home: 'होम',
    back: 'वापस',
    share: 'शेयर',
    donate: 'दान करें',
    upgrade: 'अपग्रेड',
    settings: 'सेटिंग्स',
    signOut: 'साइन आउट',
    close: 'बंद करें',
    loading: 'लोड हो रहा है...',
    heroTitle: 'AI संगीत स्टूडियो',
    heroSubtitle: '4 शब्द गाकर हिट लिखें, AI से जज हों, और अपनी आवाज में महारत हासिल करें।',
    tagline: 'AI के साथ स्टारडम का रास्ता',
    voiceClone: 'वॉइस क्लोन',
    voiceCloneDesc: 'मजेदार वाक्यों से अपनी आवाज ट्रेन करें!',
    judge: 'जज',
    judgeDesc: 'असली AGT तैयारी स्कोर पाएं।',
    danceCoach: 'डांस कोच',
    danceCoachDesc: 'स्टेज के लिए AI वीडियो डांस लेसन!',
    goldenTicket: 'गोल्डन टिकट!',
    goingToHollywood: 'आप हॉलीवुड जा रहे हैं!',
    everyChildDeservesMusic: 'हर बच्चा संगीत का हकदार है',
    iWantToHelp: 'मैं मदद करना चाहता हूं!',
    thankYouDonation: 'धन्यवाद!',
    youreAStar: 'आप एक स्टार हैं!',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
  },
  
  NL: {
    home: 'Home',
    back: 'Terug',
    share: 'Delen',
    donate: 'Doneren',
    upgrade: 'Upgraden',
    settings: 'Instellingen',
    signOut: 'Uitloggen',
    close: 'Sluiten',
    loading: 'Laden...',
    heroTitle: 'AI MUZIEKSTUDIO',
    heroSubtitle: 'Zing 4 woorden om een hit te schrijven, word beoordeeld door AI en beheers je stem.',
    voiceClone: 'Stem Klonen',
    voiceCloneDesc: 'Train je stem met leuke zinnen!',
    judge: 'De Jury',
    danceCoach: 'Danscoach',
    danceCoachDesc: 'AI-video danslessen voor het podium!',
    goldenTicket: 'GOUDEN TICKET!',
    everyChildDeservesMusic: 'Elk Kind Verdient Muziek',
    iWantToHelp: 'Ik Wil Helpen!',
    thankYouDonation: 'Dank Je!',
    language: 'Taal',
    selectLanguage: 'Selecteer Taal',
  },
  
  PL: {
    home: 'Strona główna',
    back: 'Wstecz',
    share: 'Udostępnij',
    donate: 'Wspomóż',
    upgrade: 'Ulepsz',
    settings: 'Ustawienia',
    signOut: 'Wyloguj',
    close: 'Zamknij',
    loading: 'Ładowanie...',
    heroTitle: 'STUDIO MUZYCZNE AI',
    heroSubtitle: 'Zaśpiewaj 4 słowa, aby napisać hit, bądź oceniony przez AI i opanuj swój głos.',
    voiceClone: 'Klonuj Głos',
    voiceCloneDesc: 'Trenuj swój głos zabawnymi frazami!',
    judge: 'Sędzia',
    danceCoach: 'Trener Tańca',
    danceCoachDesc: 'Wideo lekcje tańca z AI na scenę!',
    goldenTicket: 'ZŁOTY BILET!',
    everyChildDeservesMusic: 'Każde Dziecko Zasługuje na Muzykę',
    iWantToHelp: 'Chcę Pomóc!',
    thankYouDonation: 'Dziękuję!',
    language: 'Język',
    selectLanguage: 'Wybierz Język',
  },
  
  TR: {
    home: 'Ana Sayfa',
    back: 'Geri',
    share: 'Paylaş',
    donate: 'Bağış Yap',
    upgrade: 'Yükselt',
    settings: 'Ayarlar',
    signOut: 'Çıkış Yap',
    close: 'Kapat',
    loading: 'Yükleniyor...',
    heroTitle: 'AI MÜZİK STÜDYOSU',
    heroSubtitle: 'Hit yazmak için 4 kelime söyle, AI tarafından değerlendiril ve sesinize hakim ol.',
    voiceClone: 'Ses Klonla',
    voiceCloneDesc: 'Eğlenceli cümlelerle sesinizi eğitin!',
    judge: 'Jüri',
    danceCoach: 'Dans Koçu',
    danceCoachDesc: 'Sahne için AI video dans dersleri!',
    goldenTicket: 'ALTIN BİLET!',
    everyChildDeservesMusic: 'Her Çocuk Müziği Hak Eder',
    iWantToHelp: 'Yardım Etmek İstiyorum!',
    thankYouDonation: 'Teşekkürler!',
    language: 'Dil',
    selectLanguage: 'Dil Seç',
  },
};

export function getTranslation(key: string, lang: AppLanguage | string = 'EN'): string {
  const langTranslations = translations[lang] || translations.EN;
  return langTranslations[key] || translations.EN[key] || key;
}

// Shorthand function
export const t = getTranslation;
